"""交易所調閱用虛擬通貨幣流分析報告 HTML 生成器。

產出 A4 列印最佳化 HTML，結構對齊參考 PDF 範本：
封面、目錄+免責聲明、案件資訊、錢包概況、分析情形、結論及建議事項、名詞解釋。
"""

import os
from datetime import datetime

from flow_tracer import (
    FlowGraph, FlowNode, FlowEdge, CaseInfo, LAYER_LETTERS,
    classify_wallets, analyze_trx_gas,
)
from flow_report import (
    _esc, _short_addr, _ts_to_str, _ts_to_date, _format_amount,
    _tronscan_addr_link, _tronscan_tx_link, _generate_flow_svg,
)
from templates.disclaimer import EXCHANGE_REPORT_DISCLAIMER_ITEMS
from templates.glossary import EXCHANGE_REPORT_GLOSSARY_ITEMS


# --- 錢包角色中文名稱 ---

WALLET_TYPE_LABELS = {
    "relay": "中繼錢包",
    "profit": "獲利錢包",
    "mule": "車手錢包",
}


def _wallet_role_description(node: FlowNode, graph: FlowGraph) -> str:
    """根據節點屬性產生錢包角色描述。"""
    if node.is_exchange:
        name = ", ".join(node.labels) if node.labels else "交易所"
        return f"交易所地址（{name}）"
    if node.layer == 0:
        return "起始追蹤地址（被告/涉嫌人轉幣錢包）"
    if node.wallet_type == "relay":
        return "中繼錢包（用於中轉、分散資金）"
    if node.wallet_type == "profit":
        return "獲利錢包（向被害人發送假獲利）"
    return "犯嫌收款錢包"


# --- 報告生成主函式 ---

def generate_exchange_report(
    graph: FlowGraph,
    case_info: CaseInfo,
    output_path: str,
    trx_providers: dict[str, str] | None = None,
) -> str:
    """產生交易所調閱用虛擬通貨幣流分析報告 HTML。"""

    # 自動分類錢包
    classify_wallets(graph)

    now = datetime.now()
    roc_year = now.year - 1911
    report_date_roc = f"中華民國 {roc_year} 年 {now.month} 月 {now.day} 日"
    report_date = case_info.request_date or now.strftime("%Y年%m月%d日")

    # 收集所有交易序號
    tx_hashes = list(dict.fromkeys(e.tx_hash for e in graph.edges if e.tx_hash))

    # SVG 幣流圖
    svg_content = _generate_flow_svg(graph)

    # 組合 HTML
    html_content = _build_exchange_html(
        case_info=case_info,
        report_date=report_date,
        report_date_roc=report_date_roc,
        graph=graph,
        tx_hashes=tx_hashes,
        svg_content=svg_content,
        trx_providers=trx_providers or {},
    )

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    return output_path


# --- HTML 組建 ---

def _build_exchange_html(
    case_info: CaseInfo,
    report_date: str,
    report_date_roc: str,
    graph: FlowGraph,
    tx_hashes: list[str],
    svg_content: str,
    trx_providers: dict[str, str],
) -> str:
    """組建完整交易所調閱報告 HTML。"""

    cover = _build_cover(case_info, report_date_roc)
    toc_disclaimer = _build_toc_and_disclaimer()
    sec1 = _build_section1_case_info(case_info, report_date, graph, tx_hashes)
    wallet_overview = _build_wallet_overview(graph)
    sec2 = _build_section2_analysis(graph, svg_content, trx_providers)
    sec3 = _build_section3_conclusion(graph, case_info, report_date)
    sec4 = _build_section4_glossary()

    return f"""<!DOCTYPE html>
<html lang="zh-TW">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>虛擬通貨幣流分析報告 — {_esc(case_info.case_number)}</title>
<style>
{_get_exchange_report_css()}
</style>
</head>
<body>
{cover}
{toc_disclaimer}
{sec1}
{wallet_overview}
{sec2}
{sec3}
{sec4}

<footer class="page-footer">
    <span class="footer-case">{_esc(case_info.case_number)}</span>
    <span class="footer-gen">Generated by crypto-acc-chk · MistTrack AML</span>
</footer>
</body>
</html>"""


def _build_cover(case_info: CaseInfo, report_date_roc: str) -> str:
    """封面頁。"""
    return f"""
    <div class="cover page-break-after">
        <div class="cover-agency">{_esc(case_info.agency)}</div>
        {f'<div class="cover-division">{_esc(case_info.division)}</div>' if case_info.division else ''}
        <h1 class="cover-title">虛擬通貨幣流分析報告</h1>
        <div class="cover-case-info">
            {f'<p>案號：{_esc(case_info.case_number)}</p>' if case_info.case_number else ''}
            <p>案類：{_esc(case_info.case_type)}</p>
            {f'<p>案件說明：{_esc(case_info.description)}</p>' if case_info.description else ''}
        </div>
        <div class="cover-personnel">
            <table class="personnel-table">
                <tr><td>分析人員：</td><td>{_esc(case_info.analyst_rank)} {_esc(case_info.analyst_name)}</td></tr>
                <tr><td>審核人員：</td><td>{_esc(case_info.reviewer_rank)} {_esc(case_info.reviewer_name)}</td></tr>
            </table>
        </div>
        <div class="cover-date">{_esc(report_date_roc)}</div>
    </div>
    """


def _build_toc_and_disclaimer() -> str:
    """目錄 + 免責聲明頁。"""
    disclaimer_items = "\n".join(
        f'<li class="disclaimer-item">{_esc(item)}</li>'
        for item in EXCHANGE_REPORT_DISCLAIMER_ITEMS
    )
    return f"""
    <div class="toc-disclaimer page-break-after">
        <h2 class="section-title">目　錄</h2>
        <ul class="toc-list">
            <li>免責聲明</li>
            <li>一、案件資訊</li>
            <li>二、分析情形</li>
            <li>三、結論及建議事項</li>
            <li>四、名詞解釋</li>
        </ul>

        <h2 class="section-title" style="margin-top: 40px;">免責聲明</h2>
        <ol class="disclaimer-list">
            {disclaimer_items}
        </ol>
    </div>
    """


def _build_section1_case_info(
    case_info: CaseInfo,
    report_date: str,
    graph: FlowGraph,
    tx_hashes: list[str],
) -> str:
    """一、案件資訊。"""

    # 時間範圍顯示
    time_range_row = ""
    if case_info.min_timestamp or case_info.max_timestamp:
        from_str = _ts_to_date(case_info.min_timestamp // 1000) if case_info.min_timestamp else "不限"
        to_str = _ts_to_date(case_info.max_timestamp // 1000) if case_info.max_timestamp else "不限"
        time_range_row = f'<tr><th>追蹤時間範圍</th><td>{_esc(from_str)} ～ {_esc(to_str)}（僅限縮起始地址查詢範圍）</td></tr>'

    target_exchange_row = ""
    if case_info.target_exchange:
        target_exchange_row = f'<tr><th>目標交易所</th><td>{_esc(case_info.target_exchange)}（僅保留通往此交易所之路徑）</td></tr>'

    # 案件資訊表格
    info_table = f"""
    <table class="info-table">
        <tr><th>承辦單位</th><td>{_esc(case_info.agency)} {_esc(case_info.division)}</td></tr>
        <tr><th>承辦人員</th><td>{_esc(case_info.analyst_rank)} {_esc(case_info.analyst_name)}</td></tr>
        <tr><th>申請日期</th><td>{_esc(report_date)}</td></tr>
        <tr><th>案類</th><td>{_esc(case_info.case_type)}</td></tr>
        <tr><th>幣別</th><td>{_esc(case_info.coin_type)}</td></tr>
        {f'<tr><th>案號</th><td>{_esc(case_info.case_number)}</td></tr>' if case_info.case_number else ''}
        {time_range_row}
        {target_exchange_row}
    </table>
    """

    # 錢包地址清單（含層別標籤 + 角色說明）
    addr_rows = []
    for layer_idx in sorted(graph.layers.keys()):
        for addr in graph.layers[layer_idx]:
            node = graph.nodes.get(addr)
            if not node:
                continue
            role = _wallet_role_description(node, graph)
            wtype = WALLET_TYPE_LABELS.get(node.wallet_type, "")
            type_badge = f' <span class="badge badge-{node.wallet_type}">{wtype}</span>' if wtype else ""
            if node.is_exchange:
                type_badge = f' <span class="badge badge-exchange">交易所</span>'
            addr_rows.append(
                f'<tr>'
                f'<td class="mono">{_esc(node.alias)}</td>'
                f'<td class="mono addr-cell">{_esc(addr)}</td>'
                f'<td>{_esc(role)}{type_badge}</td>'
                f'</tr>'
            )

    addr_table = f"""
    <h3>錢包地址清單</h3>
    <table class="data-table">
        <thead><tr><th>層別</th><th>地址</th><th>角色說明</th></tr></thead>
        <tbody>{"".join(addr_rows)}</tbody>
    </table>
    """

    # 交易序號清單
    tx_html = ""
    if tx_hashes:
        tx_items = "\n".join(
            f'<li><code class="tx-hash">{_esc(h)}</code></li>'
            for h in tx_hashes
        )
        tx_html = f"""
        <h3>交易序號列表（共 {len(tx_hashes)} 筆）</h3>
        <ol class="tx-list">{tx_items}</ol>
        """

    return f"""
    <div class="section page-break-after">
        <h2 class="section-title">一、案件資訊</h2>
        {info_table}
        {addr_table}
        {tx_html}
    </div>
    """


def _build_wallet_overview(graph: FlowGraph) -> str:
    """錢包概況表 — 每個地址的餘額、交易統計。"""
    rows = []
    for layer_idx in sorted(graph.layers.keys()):
        for addr in graph.layers[layer_idx]:
            node = graph.nodes.get(addr)
            if not node:
                continue
            rows.append(
                f'<tr>'
                f'<td class="mono">{_esc(node.alias)}</td>'
                f'<td class="mono addr-cell">{_esc(_short_addr(addr))}</td>'
                f'<td class="num">{_format_amount(node.balance)}</td>'
                f'<td>{_ts_to_str(node.first_seen) if node.first_seen else "—"}</td>'
                f'<td>{_ts_to_str(node.last_seen) if node.last_seen else "—"}</td>'
                f'<td class="num">{_format_amount(node.total_received)}</td>'
                f'<td class="num">{node.received_txs_count}</td>'
                f'<td class="num">{_format_amount(node.total_spent)}</td>'
                f'<td class="num">{node.spent_txs_count}</td>'
                f'<td class="num">{node.txs_count}</td>'
                f'</tr>'
            )

    return f"""
    <div class="section page-break-after">
        <h3>錢包概況表</h3>
        <table class="data-table compact">
            <thead>
                <tr>
                    <th>別名</th><th>地址</th><th>餘額</th>
                    <th>首次交易</th><th>最近交易</th>
                    <th>收入總額</th><th>收入次數</th>
                    <th>支出總額</th><th>支出次數</th>
                    <th>總交易次數</th>
                </tr>
            </thead>
            <tbody>{"".join(rows)}</tbody>
        </table>
    </div>
    """


def _build_section2_analysis(
    graph: FlowGraph,
    svg_content: str,
    trx_providers: dict[str, str],
) -> str:
    """二、分析情形。"""

    # (一) 幣流視覺化圖 + 基本敘述
    narrative = _generate_narrative(graph)
    narrative_html = "\n".join(
        f"<p>{_esc(line)}</p>" for line in narrative.split("\n\n") if line.strip()
    )

    part1 = f"""
    <h3>（一）幣流視覺化圖</h3>
    <div class="flow-diagram">{svg_content}</div>
    <div class="narrative">{narrative_html}</div>
    """

    # (二) 各錢包態樣分析
    part2 = _build_wallet_analysis(graph)

    # (三) 錢包間關聯繫屬及支配情形
    part3 = _build_association_analysis(graph, trx_providers)

    # (四) 結論研判
    part4 = _build_analysis_conclusion(graph)

    return f"""
    <div class="section page-break-after">
        <h2 class="section-title">二、分析情形</h2>
        {part1}
        {part2}
        {part3}
        {part4}
    </div>
    """


def _build_wallet_analysis(graph: FlowGraph) -> str:
    """（二）各錢包態樣分析。"""
    items = []

    for layer_idx in sorted(graph.layers.keys()):
        for addr in graph.layers[layer_idx]:
            node = graph.nodes.get(addr)
            if not node:
                continue

            role = _wallet_role_description(node, graph)
            label_str = f"（{', '.join(node.labels)}）" if node.labels else ""

            detail_parts = [f"<strong>{_esc(node.alias)}</strong>：{_esc(role)}{_esc(label_str)}"]

            if node.total_received > 0:
                detail_parts.append(
                    f"累計收入 {_format_amount(node.total_received)}，"
                    f"累計支出 {_format_amount(node.total_spent)}"
                )
                if node.total_received > 0 and not node.is_exchange:
                    ratio = node.total_spent / node.total_received * 100
                    detail_parts.append(f"轉出比例 {ratio:.1f}%")

            if node.risk_level:
                detail_parts.append(f"風險等級：{_esc(node.risk_level)}（{node.risk_score} 分）")

            items.append(
                f'<div class="wallet-card">'
                f'<p>{"，".join(detail_parts)}。</p>'
                f'</div>'
            )

    return f"""
    <h3>（二）各錢包態樣分析</h3>
    <div class="wallet-analysis">{"".join(items)}</div>
    """


def _build_association_analysis(
    graph: FlowGraph,
    trx_providers: dict[str, str],
) -> str:
    """（三）錢包間關聯繫屬及支配情形。"""
    parts = []

    # TRX 油費關聯分析
    if trx_providers:
        trx_rows = []
        for addr, provider in trx_providers.items():
            node = graph.nodes.get(addr)
            alias = node.alias if node else _short_addr(addr)
            prov_node = graph.nodes.get(provider)
            prov_alias = prov_node.alias if prov_node else _short_addr(provider)
            trx_rows.append(
                f'<tr>'
                f'<td class="mono">{_esc(alias)}</td>'
                f'<td class="mono addr-cell">{_esc(_short_addr(addr))}</td>'
                f'<td class="mono">{_esc(prov_alias)}</td>'
                f'<td class="mono addr-cell">{_esc(_short_addr(provider))}</td>'
                f'</tr>'
            )
        parts.append(f"""
        <h4>TRX 油費關聯分析</h4>
        <p>以下列出各非交易所錢包之 TRX（交易手續費）入帳來源。提供 TRX 油費之地址，
        即可能為該錢包之實際持有人或上游控制者：</p>
        <table class="data-table compact">
            <thead><tr><th>錢包別名</th><th>錢包地址</th><th>TRX 提供者別名</th><th>TRX 提供者地址</th></tr></thead>
            <tbody>{"".join(trx_rows)}</tbody>
        </table>
        """)
    else:
        parts.append("<h4>TRX 油費關聯分析</h4><p>本次分析未發現顯著之 TRX 油費關聯。</p>")

    # 資金流向關聯
    assoc_lines = _generate_association_text(graph)
    if assoc_lines:
        assoc_html = "\n".join(f"<p>{_esc(line)}</p>" for line in assoc_lines)
        parts.append(f"""
        <h4>資金流向關聯</h4>
        <div class="narrative">{assoc_html}</div>
        """)

    return f"""
    <h3>（三）錢包間關聯繫屬及支配情形</h3>
    {"".join(parts)}
    """


def _build_analysis_conclusion(graph: FlowGraph) -> str:
    """（四）結論研判。"""
    exchange_nodes = [n for n in graph.nodes.values() if n.is_exchange]
    relay_nodes = [n for n in graph.nodes.values() if n.wallet_type == "relay"]
    profit_nodes = [n for n in graph.nodes.values() if n.wallet_type == "profit"]

    lines = []

    total_amount = sum(e.amount for e in graph.edges)
    token = graph.coin_type.split("-")[0] if "-" in graph.coin_type else graph.coin_type
    lines.append(
        f"經幣流分析，本案起始地址之資金經 {len(graph.nodes)} 個相關地址、"
        f"{len(graph.edges)} 筆交易流轉，涉及金額共計約 {_format_amount(total_amount, token)}。"
    )

    if relay_nodes:
        aliases = "、".join(n.alias for n in relay_nodes)
        lines.append(f"其中地址 {aliases} 經研判為中繼錢包，用於中轉分散資金。")

    if profit_nodes:
        aliases = "、".join(n.alias for n in profit_nodes)
        lines.append(f"地址 {aliases} 經研判為獲利錢包，曾向上游地址反向發送小額虛擬貨幣。")

    if exchange_nodes:
        exchange_names: dict[str, list[str]] = {}
        for n in exchange_nodes:
            name = ", ".join(n.labels) if n.labels else "未知交易所"
            exchange_names.setdefault(name, []).append(n.alias)
        for name, aliases in exchange_names.items():
            lines.append(f"資金最終流入 {name}（地址 {'、'.join(aliases)}）。")
        lines.append("建議向上述交易所調閱對應地址之 KYC 帳戶資料及交易紀錄。")
    else:
        lines.append("本次追蹤範圍內尚未發現資金流入已知交易所，建議擴大追蹤深度或透過其他偵查手段追查。")

    conclusion_html = "\n".join(f"<p>{_esc(line)}</p>" for line in lines)

    return f"""
    <h3>（四）結論研判</h3>
    <div class="narrative">{conclusion_html}</div>
    """


def _build_section3_conclusion(
    graph: FlowGraph,
    case_info: CaseInfo,
    report_date: str,
) -> str:
    """三、結論及建議事項。"""
    exchange_nodes = [n for n in graph.nodes.values() if n.is_exchange]

    summary_lines = []
    total_amount = sum(e.amount for e in graph.edges)
    token = graph.coin_type.split("-")[0] if "-" in graph.coin_type else graph.coin_type

    # 組建摘要（含時間範圍資訊）
    time_desc = ""
    if case_info.min_timestamp or case_info.max_timestamp:
        from_str = _ts_to_date(case_info.min_timestamp // 1000) if case_info.min_timestamp else "不限"
        to_str = _ts_to_date(case_info.max_timestamp // 1000) if case_info.max_timestamp else "不限"
        time_desc = f"犯罪時間 {from_str} ～ {to_str} 期間，"

    target_desc = ""
    if case_info.target_exchange:
        target_desc = f"（已篩選僅通往 {case_info.target_exchange} 之路徑）"

    summary_lines.append(
        f"本報告針對起始地址（{_short_addr(graph.source_address)}）進行幣流追蹤分析，"
        f"{time_desc}"
        f"共追蹤 {len(graph.nodes)} 個相關地址，涉及 {len(graph.edges)} 筆交易，"
        f"金額共計約 {_format_amount(total_amount, token)}{target_desc}。"
    )

    suggestions = []
    if exchange_nodes:
        exchange_names: dict[str, list[str]] = {}
        for n in exchange_nodes:
            name = ", ".join(n.labels) if n.labels else "未知交易所"
            exchange_names.setdefault(name, []).append(n.alias)
        for i, (name, aliases) in enumerate(exchange_names.items(), 1):
            addr_list = []
            for n in exchange_nodes:
                n_name = ", ".join(n.labels) if n.labels else "未知交易所"
                if n_name == name:
                    addr_list.append(n.address)
            # 計算流入該交易所的金額
            exchange_addrs = set(n.address for n in exchange_nodes
                                if (", ".join(n.labels) if n.labels else "未知交易所") == name)
            inflow = sum(e.amount for e in graph.edges if e.to_address in exchange_addrs)
            if time_desc and inflow > 0:
                inflow_desc = (
                    f"經追蹤，{time_desc}從起始地址轉出之 "
                    f"{_format_amount(inflow, token)} 經中繼後流入 {name}，"
                )
            else:
                inflow_desc = ""
            suggestions.append(
                f"{i}. {inflow_desc}"
                f"建議向 {name} 調閱地址 {'、'.join(aliases)} 之註冊帳戶資料"
                f"（含 KYC 身分資訊）及相關交易紀錄，以釐清資金實際受益人身分。"
            )

    suggestions.append(
        f"{len(suggestions) + 1}. 本報告之幣流圖及錢包概況表可匯出為圖檔或 CSV 作為偵查卷證附件。"
    )

    summary_html = "\n".join(f"<p>{_esc(l)}</p>" for l in summary_lines)
    suggestions_html = "\n".join(f"<p class='indent'>{_esc(s)}</p>" for s in suggestions)

    return f"""
    <div class="section page-break-after">
        <h2 class="section-title">三、結論及建議事項</h2>
        <div class="conclusion">
            {summary_html}
            <h3>建議事項</h3>
            {suggestions_html}
        </div>

        <div class="sign-block">
            <table class="sign-table">
                <tr>
                    <td>報告日期：{_esc(report_date)}</td>
                    <td>頁數：本報告共含封面、目錄、正文及附件</td>
                </tr>
                <tr>
                    <td>分析人員：{_esc(case_info.analyst_rank)} {_esc(case_info.analyst_name)}</td>
                    <td>審核人員：{_esc(case_info.reviewer_rank)} {_esc(case_info.reviewer_name)}</td>
                </tr>
            </table>
        </div>
    </div>
    """


def _build_section4_glossary() -> str:
    """四、名詞解釋。"""
    items_html = "\n".join(
        f'<dt>{_esc(item["term"])}</dt><dd>{_esc(item["definition"])}</dd>'
        for item in EXCHANGE_REPORT_GLOSSARY_ITEMS
    )

    return f"""
    <div class="section">
        <h2 class="section-title">四、名詞解釋</h2>
        <dl class="glossary">{items_html}</dl>
        <div class="report-end">— 報告結束 —</div>
    </div>
    """


# --- 分析敘述自動生成 ---

def _generate_narrative(graph: FlowGraph) -> str:
    """依拓撲順序走訪 FlowGraph 的 edges，生成中文分析敘述。

    同一對 (from, to) 的多筆交易聚合為一段，避免重複敘述。
    """
    if not graph.edges:
        return "本案未追蹤到任何交易紀錄。"

    paragraphs = []

    # 聚合同一對 (from, to) 的邊：加總金額、取最早時間、計算筆數
    pair_agg: dict[tuple[str, str], dict] = {}
    for edge in graph.edges:
        key = (edge.from_address, edge.to_address)
        if key not in pair_agg:
            pair_agg[key] = {
                "total_amount": 0.0,
                "token": edge.token,
                "earliest_ts": edge.timestamp,
                "latest_ts": edge.timestamp,
                "tx_count": 0,
            }
        agg = pair_agg[key]
        agg["total_amount"] += edge.amount
        agg["tx_count"] += 1
        if edge.timestamp and (agg["earliest_ts"] == 0 or edge.timestamp < agg["earliest_ts"]):
            agg["earliest_ts"] = edge.timestamp
        if edge.timestamp and edge.timestamp > agg["latest_ts"]:
            agg["latest_ts"] = edge.timestamp

    # 按 from_node.layer → earliest_ts 排序
    sorted_pairs = sorted(pair_agg.items(), key=lambda item: (
        graph.nodes.get(item[0][0], FlowNode("", 0, "")).layer,
        item[1]["earliest_ts"],
    ))

    for (from_addr, to_addr), agg in sorted_pairs:
        from_node = graph.nodes.get(from_addr)
        to_node = graph.nodes.get(to_addr)
        if not from_node or not to_node:
            continue

        amount_str = _format_amount(agg["total_amount"], agg["token"])
        tx_count = agg["tx_count"]

        # 時間描述
        if agg["earliest_ts"] == agg["latest_ts"] or tx_count == 1:
            date_str = _ts_to_str(agg["earliest_ts"]) if agg["earliest_ts"] else "未知時間"
            time_desc = f"於 {date_str}"
        else:
            start_str = _ts_to_str(agg["earliest_ts"]) if agg["earliest_ts"] else "未知時間"
            end_str = _ts_to_str(agg["latest_ts"]) if agg["latest_ts"] else "未知時間"
            time_desc = f"於 {start_str} 至 {end_str} 期間"

        count_desc = f"（共 {tx_count} 筆交易）" if tx_count > 1 else ""

        line = (
            f"地址 {from_node.alias}（{_short_addr(from_addr)}）"
            f"{time_desc}將 {amount_str} 轉出至"
            f"地址 {to_node.alias}（{_short_addr(to_addr)}）{count_desc}"
        )

        if to_node.is_exchange:
            exchange_name = ", ".join(to_node.labels) if to_node.labels else "交易所"
            line += f"。經查地址 {to_node.alias} 為 {exchange_name} 之地址"

        wtype = WALLET_TYPE_LABELS.get(to_node.wallet_type, "")
        if wtype:
            line += f"（經研判為{wtype}）"

        line += "。"
        paragraphs.append(line)

    return "\n\n".join(paragraphs)


def _generate_association_text(graph: FlowGraph) -> list[str]:
    """依幣流圖判斷各錢包間的從屬與支配關係。"""
    lines = []

    # 建立邊的索引
    outgoing: dict[str, list[FlowEdge]] = {}
    for edge in graph.edges:
        outgoing.setdefault(edge.from_address, []).append(edge)

    for layer_idx in sorted(graph.layers.keys()):
        for addr in graph.layers[layer_idx]:
            node = graph.nodes.get(addr)
            if not node or node.is_exchange:
                continue

            out_edges = outgoing.get(addr, [])
            if not out_edges:
                continue

            targets = []
            for e in out_edges:
                to_node = graph.nodes.get(e.to_address)
                if to_node:
                    targets.append(to_node.alias)

            if targets:
                unique_targets = list(dict.fromkeys(targets))
                lines.append(
                    f"地址 {node.alias} 將資金轉出至 {'、'.join(unique_targets)}，"
                    f"研判 {node.alias} 與 {'、'.join(unique_targets)} 間具有資金從屬關係。"
                )

    return lines


# --- CSS ---

def _get_exchange_report_css() -> str:
    """交易所調閱報告列印優化 CSS — A4 頁面。"""
    return """
/* === 基礎排版 === */
@page {
    size: A4;
    margin: 20mm 18mm 25mm 18mm;
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: "Noto Sans TC", "Microsoft JhengHei", "PingFang TC",
                 -apple-system, BlinkMacSystemFont, sans-serif;
    font-size: 12pt;
    line-height: 1.8;
    color: #222;
    background: #fff;
    max-width: 210mm;
    margin: 0 auto;
    padding: 20mm 18mm;
}

@media screen {
    body {
        padding: 40px;
        max-width: 900px;
        box-shadow: 0 0 20px rgba(0,0,0,0.1);
    }
}

/* === 分頁控制 === */
.page-break-after {
    page-break-after: always;
}

@media screen {
    .page-break-after {
        border-bottom: 2px dashed #ccc;
        padding-bottom: 40px;
        margin-bottom: 40px;
    }
}

/* === 封面 === */
.cover {
    text-align: center;
    padding-top: 80px;
    min-height: 700px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}

.cover-agency {
    font-size: 20pt;
    font-weight: 700;
    letter-spacing: 6px;
    margin-bottom: 8px;
}

.cover-division {
    font-size: 14pt;
    color: #555;
    margin-bottom: 40px;
}

.cover-title {
    font-size: 28pt;
    font-weight: 900;
    letter-spacing: 8px;
    margin-bottom: 50px;
    border-bottom: 3px solid #333;
    padding-bottom: 16px;
}

.cover-case-info {
    font-size: 13pt;
    line-height: 2.2;
    margin-bottom: 30px;
}

.cover-personnel {
    margin-bottom: 40px;
}

.personnel-table {
    margin: 0 auto;
    font-size: 12pt;
    border: none;
}

.personnel-table td {
    padding: 4px 12px;
    text-align: left;
}

.cover-date {
    font-size: 14pt;
    margin-top: 20px;
    letter-spacing: 2px;
}

/* === 目錄 + 免責 === */
.toc-disclaimer {
    padding-top: 40px;
}

.toc-list {
    list-style: none;
    padding: 0;
    font-size: 13pt;
    line-height: 2.5;
}

.toc-list li {
    border-bottom: 1px dotted #ccc;
    padding: 4px 0;
}

.disclaimer-list {
    padding-left: 24px;
    margin-top: 12px;
}

.disclaimer-item {
    font-size: 11pt;
    line-height: 1.8;
    margin-bottom: 12px;
    text-align: justify;
}

/* === 段落標題 === */
.section {
    padding-top: 20px;
}

.section-title {
    font-size: 18pt;
    font-weight: 700;
    margin-bottom: 20px;
    padding-bottom: 8px;
    border-bottom: 2px solid #333;
}

h3 {
    font-size: 14pt;
    font-weight: 600;
    margin-top: 24px;
    margin-bottom: 12px;
    color: #333;
}

h4 {
    font-size: 12pt;
    font-weight: 600;
    margin-top: 16px;
    margin-bottom: 8px;
    color: #444;
}

/* === 案件資訊表格 === */
.info-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 20px;
    font-size: 11pt;
}

.info-table th,
.info-table td {
    border: 1px solid #999;
    padding: 8px 12px;
    text-align: left;
}

.info-table th {
    background: #f0f0f0;
    width: 120px;
    font-weight: 600;
}

/* === 資料表格 === */
.data-table {
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0 20px;
    font-size: 10pt;
}

.data-table th,
.data-table td {
    border: 1px solid #aaa;
    padding: 6px 8px;
    text-align: left;
}

.data-table thead th {
    background: #f0f0f0;
    font-weight: 600;
    font-size: 9pt;
    white-space: nowrap;
}

.data-table.compact td {
    padding: 4px 6px;
    font-size: 9pt;
}

.mono {
    font-family: "SF Mono", "Fira Code", "Consolas", monospace;
}

.addr-cell {
    font-size: 8pt;
    word-break: break-all;
}

.num {
    text-align: right;
    white-space: nowrap;
}

/* === 標籤徽章 === */
.badge {
    display: inline-block;
    padding: 1px 6px;
    border-radius: 3px;
    font-size: 8pt;
    font-weight: 600;
    margin-left: 4px;
    vertical-align: middle;
}

.badge-relay {
    background: #E3F2FD;
    color: #1565C0;
    border: 1px solid #90CAF9;
}

.badge-profit {
    background: #FFF3E0;
    color: #E65100;
    border: 1px solid #FFCC80;
}

.badge-mule {
    background: #FCE4EC;
    color: #C62828;
    border: 1px solid #EF9A9A;
}

.badge-exchange {
    background: #E8F5E9;
    color: #2E7D32;
    border: 1px solid #A5D6A7;
}

/* === 幣流分析圖 === */
.flow-diagram {
    overflow-x: auto;
    margin: 16px 0;
    padding: 12px;
    border: 1px solid #ddd;
    border-radius: 4px;
    background: #fff;
    text-align: center;
}

.flow-diagram svg {
    max-width: 100%;
    height: auto;
}

/* === 錢包分析卡片 === */
.wallet-analysis {
    margin: 12px 0;
}

.wallet-card {
    padding: 8px 12px;
    margin-bottom: 8px;
    border-left: 3px solid #1976D2;
    background: #FAFAFA;
    font-size: 11pt;
    line-height: 1.6;
}

/* === 分析敘述 === */
.narrative p,
.conclusion p,
.disclaimer-text p {
    text-indent: 2em;
    margin-bottom: 8px;
    text-align: justify;
}

.conclusion p.indent {
    text-indent: 4em;
}

/* === 名詞解釋 === */
.glossary {
    margin-top: 12px;
}

.glossary dt {
    font-weight: 700;
    font-size: 11pt;
    margin-top: 16px;
    margin-bottom: 4px;
}

.glossary dd {
    font-size: 11pt;
    line-height: 1.8;
    text-align: justify;
    margin-left: 0;
    margin-bottom: 8px;
}

/* === 報告結束 === */
.report-end {
    text-align: center;
    margin-top: 40px;
    padding-top: 20px;
    border-top: 2px solid #333;
    font-size: 12pt;
    font-weight: 600;
    color: #555;
    letter-spacing: 4px;
}

/* === 簽章欄 === */
.sign-block {
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid #ccc;
}

.sign-table {
    width: 100%;
    border: none;
    font-size: 11pt;
}

.sign-table td {
    padding: 8px 0;
    width: 50%;
    vertical-align: top;
}

/* === 交易序號 === */
.tx-list {
    padding-left: 24px;
    font-size: 10pt;
}

.tx-list li {
    padding: 2px 0;
}

.tx-hash {
    font-family: "SF Mono", "Fira Code", "Consolas", monospace;
    font-size: 8pt;
    background: #f5f5f5;
    padding: 2px 4px;
    border-radius: 3px;
    word-break: break-all;
}

/* === 頁尾 === */
.page-footer {
    display: flex;
    justify-content: space-between;
    margin-top: 40px;
    padding-top: 12px;
    border-top: 1px solid #ccc;
    font-size: 8pt;
    color: #999;
}

@media print {
    .page-footer {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        padding: 8px 18mm;
    }

    body {
        padding: 0;
        max-width: none;
    }
}
"""
